### ISSUE TITLE
Error: not found

### ISSUE THREAD

**Issue by mauvehed** [actions-marketplace-validations/akhilmhdh_contributors-readme-action#1]
While running the following workflow manually

```

# Inserts list of community members into ./README.md
name: Add contributors to README
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '10 2 * * 0' # At 02:10 on Sunday.

jobs:
  insert-contributors:
    runs-on: ubuntu-latest
    name: Add contributors
    steps:
      - name: Updates readme with contributors
        uses: akhilmhdh/contributors-readme-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image_size: 80
          readme_path: .github/README.md
          columns_per_row: 6
          commit_message: 'chore(README.md): updates contributors list'
```

It fails with this incredibly unhelpful error

```
Run akhilmhdh/contributors-readme-action@master
  with:
    image_size: 80
    readme_path: .github/README.md
    columns_per_row: 6
    commit_message: chore(README.md): updates contributors list
    use_username: false
    collaborators: direct
    auto_detect_branch_protection: true
    pr_title_on_protected: docs(contributor): contributors readme action update
  env:
    GITHUB_TOKEN: ***
Error: Not Found
```
